[project]
name = "ibmcloud-base-agent"
version = "0.1.0"
description = "Base for IBMCloud Agent (A2A-compliant)"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "a2a-server>=0.1.5",
    "google-adk>=0.2.0",
    "litellm>=1.67.0",
    "python-dotenv>=1.1.0",
]
