[project]
name = "ibmcloud-base-agent"
version = "0.1.0"
description = "Base for IBMCloud Agent (A2A-compliant)"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "a2a-json-rpc>=0.1.3",
    "asyncio>=3.4.3",
    "pydantic>=2.11.3",
    "fastapi>=0.115.12",
    "uvicorn>=0.34.1",
    "httpx>=0.28.1",
    "pyyaml>=6.0.2",
    "a2a-server>=0.1.7",
    "aiofiles>=24.1.0",
    "chuk-llm>=0.1.3",
    "chuk-session-manager>=0.1.0",
    "google-adk>=0.2.0",
    "litellm>=1.67.0",
    "opentelemetry-exporter-otlp>=1.33.1",
    "opentelemetry-exporter-prometheus>=0.54b1",
    "opentelemetry-sdk>=1.33.1",
    "prometheus-client>=0.22.0",
    "python-dotenv>=1.1.0",
]
